# promptfooconfig.yaml
description: "Multiline prompt demo"
providers:
  - openai:gpt-4o                                 # OpenAI model ID
  - anthropic:messages:claude-sonnet-4-20250514   # Claude Sonnet model ID

prompts:
  - |-
    You are a helpful assistant.

    Please answer the following question:
    {{question}}

    Provide a detailed explanation.

tests:
  - vars:
      question: "Why is the sky blue?"