# promptfooconfig.yaml
description: "Config providers demo"
providers:
  - id: openai:gpt-4.1
    config:
      temperature: 0.7
      max_tokens: 150
  - id: anthropic:messages:claude-sonnet-4-20250514
    config:
      temperature: 0.7
      max_tokens: 150

prompts:
  - 'Translate the following text to French: "{{text}}"'

tests:
  - vars:
      text: "Hello, how are you?"