prompts:
  - file://prompts/non_empathetic_assistant.txt
  # - file://prompts/empathetic_assistant.txt

providers:
  - file://providers/providers_temp_0.7.yaml
  - file://providers/providers_temp_1.yaml

tests:
  - file://tests/empathetic_test.yaml
  # - file://tests/non_empathetic_test.yaml
