# 1) Launch tweet: quality + performance budget
description: "Ensure the tweet is enthusiastic, under 50 words, mentions AI, and stays cheap & fast."
providers:
  - id: openai:gpt-4o-mini
    config:
      temperature: 0.7
      max_tokens: 80

prompts:
  - "Write a tweet announcing our new AI product."

tests:
  - threshold: 0.7
    assert:
      - type: llm-rubric
        value: "Enthusiastic, promotional, and under 50 words."
        weight: 2
        metric: Tone
      - type: contains
        value: "AI"
        weight: 1
        metric: Tone
      - type: assert-set
        metric: Performance
        assert:
          - type: cost
            threshold: 0.001
          - type: latency
            threshold: 200