# yaml-language-server: $schema=https://promptfoo.dev/config-schema.json

# Learn more about building a configuration: https://promptfoo.dev/docs/configuration/guide

description: "My eval"

prompts:
  - "Write a tweet about {{topic}}"
  - "Write a concise, funny tweet about {{topic}}"
  

providers:
  - "openai:gpt-5-mini"
  - "openai:gpt-5"
  - "anthropic:claude-sonnet-4-20250514"
  

tests:
  - vars:
      topic: cars

  - vars:
      topic: muscle cars
    assert:
      # For more information on assertions, see https://promptfoo.dev/docs/configuration/expected-outputs

      # Make sure output contains the word "avocado"
      - type: icontains
        value: car

      # Prefer shorter outputs
      - type: javascript
        value: 1 / (output.length + 1)

  - vars:
      topic: new york city
    assert:
      # For more information on model-graded evals, see https://promptfoo.dev/docs/configuration/expected-outputs/model-graded
      # - type: equals
      #   value: 'cars'

      - type: contains-any
        value:
          - 'NYC'
          - 'New York City'
          - 'New York'